<a href="https://colab.research.google.com/github/sulav063/Machine_Learning_Workshop/blob/main/Introduction_to_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy

*   Creating single dimesnional arrays ✅
*   Multi dimensional array ✅
*   Randomly generated arrays ✅
*   Element wise opetations ✅
*   Summarizing operations ✅


## Single Dimensional Array

In [ ]:
import numpy as np

In [ ]:
# Create an array with all the elemests zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
#creating an array with all the  elememts one
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# create an array of size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [ ]:
np.array([1, 2, 3, 5,5])

array([1, 2, 3, 5, 5])

In [ ]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
# create an array with evenly spaced numbers within a specified range
np.linspace(0, 100, 6)

array([  0.,  20.,  40.,  60.,  80., 100.])

## Multidimensional Arrays


In [ ]:
#matrix with al elements 0
np.zeros([3, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# square matrix  with all elemets 1
np.ones([4, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# square matrix 3 by 3 with elemnts starting from 1 to 9
np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a= np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# replacing a array
a[0, 1]=20
print(a)

[[ 1 20  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
# last row all 1
a[2] = [1, 1, 1]
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [ ]:
# last column all 2
a[:, 2]= [2, 2, 2]
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [ ]:
# 3 by 3 matrix all elements 10
np.full((3, 3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

## Randomly Generated Array
- Numpy can create arrays filled with random numbers
- To ensure the reproducibility, you can set a seed using ```np.random.seed()```. It will generate the exact same random numbers for each executions.
- If you remove or change the seed values, the sequence of random numbers will be changed.

In [ ]:
np.random.rand(5)

array([0.16310865, 0.49668312, 0.0015229 , 0.32672591, 0.05964549])

In [ ]:
np.random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [ ]:
np.random.randn(5,2)

array([[ 0.52748874,  0.73388005],
       [ 0.07059861, -0.89858781],
       [ 1.8982376 , -0.09392472],
       [-0.2575987 , -1.50623833],
       [ 0.38621153, -0.05977924]])

In [ ]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[73, 63],
       [35, 69],
       [65, 12],
       [56, 93],
       [78, 90]])

## Elements wise operation on entire arrays element by element

In [ ]:
import numpy as np
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
b=(10+(a+2))
b

array([12, 13, 14, 15, 16])

In [ ]:
a

array([0, 1, 2, 3, 4])

In [ ]:
a= a*5
a

array([  0, 125, 250, 375, 500])

In [ ]:
a>=2

array([False,  True,  True,  True,  True])

In [ ]:
a>b

array([False,  True,  True,  True,  True])

In [ ]:
# summarization of thr data
# Numpy provides function for sumarizing array data
a.std()

176.7766952966369

In [ ]:
a.min()

0

In [ ]:
a.max()

500

In [ ]:
a.sum()

1250